version: "3.8"

services:
  app:
    build: .
    image: pinkbean
    depends_on:
      - db
      - redis
  redis:
    image: redis
    restart: on-failure
    volumes:
      - redis_data:/data
  db:
    image: postgres
    restart: on-failure
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/pg_init:/docker-entrypoint-initdb.d
    ports:
      - "6543:5432"
    env_file:
      - .env

volumes:
  redis_data:
  db_data:
  
